name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clean old Jekyll cache
        run: rm -rf .jekyll-cache

      - name: Fix permissions
        run: chmod -R 777 ${{ github.workspace }}

      - name: Build site in Docker
        run: |
          docker run --user $(id -u):$(id -g) -v ${{ github.workspace }}:/srv/jekyll jekyll/builder:latest \
          jekyll build --future --destination /srv/jekyll/_site

      - name: List _site contents
        run: ls -la _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
